### ISSUE TITLE
Add support for exception analysis.

### ISSUE THREAD

**Issue by sgrove** [cristianoc/reanalyze#28]
We've found cases where we used a Pervasives, atd, or yojson function without a proper try/catch, and it didn't hit us until it was in production, at which point the lack any meaningful stack traces in Async Reason meant that we had a challenging time tracking down the source.

This is made worse by the fact that our code base has grown into using the `Result` type, and there are still a few places that throw *even in our own code*. Now that we've grown to a certain size and experience, it'd be nice if we had a way of generating a TODO list to clean up all of these exceptions, and to *know* that they could never throw and escape the type system.

**Comment by cristianoc** [comment]
Thank you for bringing up this issue, and for our conversation about it.

Here are some preliminary notes for a possible design.
The goal is to guide the user towards progressively replacing exceptions by other mechanisms, such as option or result types.
In truly **exceptional** circumstances, you would want to just add annotations to acknowledge intentional uses of exceptions and what areas of code are affected by them.
If you use exceptions extensively, and want to continue doing so, this analysis won't be helpful.

Some design thoughts:

- You need to opt into exception checking.
- Any function that throws exceptions gives a warning.
- An annotation is supported to acknowledge that the function throws (those) exceptions.
- Even when a function is annotated, any user of that function that does not catch the exceptions will get a waring. Unless the user itself is annotated, and so on.
- Enough knowledge needs to be made available somehow of what library functions throw what exceptions.

**Comment by cristianoc** [comment]
To test the ideas quickly, one could build an extremely simplified prototype that:
- Operates at the level of individual value definitions, disregarding nesting.
- Does not distinguish between kinds of exceptions.
- Only checks if there is some occurrence of an exception-catching mechanism.

That rough first experiment would be very imprecise, but could give a feel for the process to follow when using such an analysis. Before the full analysis is built.

**Comment by cristianoc** [comment]
Progress here https://github.com/cristianoc/reanalyze/pull/29
And here https://github.com/cristianoc/reanalyze/pull/32

**Comment by cristianoc** [comment]
https://github.com/cristianoc/reanalyze/pull/34

**Comment by cristianoc** [comment]
https://github.com/cristianoc/reanalyze/pull/35

**Comment by cristianoc** [comment]
@sgrove this is the first full-featured iteration, except it can't read annotations across files.
So if an annotation is added to `A.re`, and `B.re` uses `A.re`, then `B.re` will not see any annotations from `A`.

**Comment by cristianoc** [comment]
https://github.com/cristianoc/reanalyze/pull/36

**Comment by cristianoc** [comment]
https://github.com/cristianoc/reanalyze/pull/37

**Comment by cristianoc** [comment]
https://github.com/cristianoc/reanalyze/pull/38

**Comment by cristianoc** [comment]
https://github.com/cristianoc/reanalyze/commit/e2a82b0140c54c8b055393bad5a962a533dd518a

**Comment by cristianoc** [comment]
https://github.com/cristianoc/reanalyze/pull/39

**Comment by cristianoc** [comment]
A feature-complete version is in release 1.8.0
https://github.com/cristianoc/reanalyze/releases/tag/v1.8.0
